# Key settings (must edit)
project_title: KD4014 Checklist
project_repo: lucydot/KD4014-Checklist
admins:
- lucydot
instructors:
- lucydot
- prakayastha
students:
- lucydot
web_address: https://lucydot.github.io/KD4014-Checklist

# User options (may edit)
questions: true
votes_required: 4
gh-pages: true
gh-pages_branch: gh-pages



