# Key settings (must edit)
project_title: Checklist for KD4014 (2022)
project_repo: lucydot/KD4014-ChooChoo
admins:
- lucydot
instructors:
- lucydot
- prakayastha
students:
- lucydot
web_address: https://lucydot.github.io/KD4014-ChooChoo

# User options (may edit)
questions: true
votes_required: 4
gh-pages: true
gh-pages_branch: gh-pages



